# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    blacklistedKernelModules = [
      "psmouse"
      "nouveau"
    ];
    initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "vmd"
      "nvme"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    kernelParams = [
      "i915.enable_psr=0"
      # enable_guc=2 (submission only, no HuC auth) instead of 3: HuC
      # involvement in engine-level resets was implicated in a GPU HANG on
      # rcs0 (CanvasRenderer/WebGL) where the reset itself timed out and
      # took the whole machine down instead of just the GPU/compositor.
      "i915.enable_guc=2"
      # Fall back to a whole-GPU reset instead of leaving the engine stuck
      # after a failed per-engine reset.
      "i915.reset=2"
      "i2c_designware.pm_disabled=1"
    ];
    extraModulePackages = [ ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
